### PR TITLE
Force number type on texturePadding to avoid type error in MaxRectsPa…

### PR DESCRIPTION
**Pull request by damienmortini**
…cker when using cli

### CODE REVIEW

**Comment by soimy** [comment]
@damienmortini First thanks for the great contribution to this repo!
It is good to have type restriction which avoids uncaught error.  If we are going to implement this, a better choice is doing type-check at parameter process: https://github.com/soimy/msdf-bmfont-xml/blob/e22589b8681fc1e2d19ce4a205e3879819cb7ab1/index.js#L87-L101

I think adding type restriction in `utils.valueQueue` as a second parameter is good. Can you do this?

**Comment by Mikecoon** [comment]
Thanks God for this PR, it saved my life.

Have no idea why it merged so far, tool doesn't work without this fix at all.

**Comment by soimy** [comment]
@Mikecoon Thanks for the mention, I haven't even realized this type issue broke the whole process! I'll do a quick merge and a better fix soon.

**Comment by soimy** [comment]
A better fix via commit d3030e69e48a6d77054e1d3808280c222d579d15
And a new patch version `2.4.1` published.

**Pull request merged**
