### PR TITLE
Support 'fontBuffer' parameter for in-memory generation.

### LINKED ISSUE #47: Support fontBuffer as alternative to fontPath
I'm migrating https://msdf-bmfont.donmccurdy.com/ (which is basically a web GUI for creating MSDF fonts...) to a newer version of my web hosting service. The new platform version doesn't allow writing anything to disk — but on the bright side it's much cheaper to run!

At this point I've got everything working, except that this package requires `fontPath` as a path on disk. The `opentype` dependency has a `opentype.parse(buffer)` method that should be able to handle a Buffer object instead.

If I write up a PR adding `fontBuffer` support, would you be open to merging that? Proposed API:

```js
generateBMFont(fontBuffer, opt, (error, textures, font) => {
  ...
});
```

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #47.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Could I talk you into an updated npm release? 😇

**Comment by soimy** [comment]
ASAP 👌

**Comment by soimy** [comment]
Updated to 2.5.3

**Comment by donmccurdy** [comment]
It's working great, thank you! Happy Chinese New Year! 🙂

**Pull request merged**
